title: Sparrowling Docs
description: Documentation for Sparrowling, a minimal and security-minded Linux distribution.
#theme: jekyll-theme-minimal
#theme: jekyll-theme-cayman
#theme: jekyll-theme-architect
#theme: jekyll-theme-dinky       #ugly
#theme: jekyll-theme-hacker  #ugly
#theme: jekyll-theme-time-machine  #ugly
#theme: jekyll-theme-tactile #retry
#theme: jekyll-theme-leap-day  #ugly
#theme: jekyll-theme-merlot  #looks okay
#theme: jekyll-theme-midnight
#theme: jekyll-theme-minima
theme: jekyll-theme-modernist
#theme: jekyll-theme-slate
show_downloads: true
