title: Sparrowling Docs
description: Documentation for Sparrowling, a minimal and security-minded Linux distribution.
#theme: jekyll-theme-minimal
#theme: jekyll-theme-cayman
#theme: jekyll-theme-architect
#theme: jekyll-theme-dinky       #ugly
#theme: jekyll-theme-hacker  #ugly
theme: jekyll-theme-time-machine
show_downloads: true
